[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tumorvolumetrics"
version = "0.1.0"
description = "A PySide6-based desktop application for analyzing tumor volume data"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "GNU AFFERO"}

authors = [
    {name = "Dennis A. Dean II", email = "dennis.a.dean@gmail.com"}
]

dependencies = [
    # GUI Framework
    "PySide6==6.10.2",

    # Data & Scientific Computing
    "numpy==2.4.2",
    "pandas<=3.0.0",
    "scipy==1.17.0",
    "matplotlib==3.10.8",

    # Statistical Analysis
    "lifelines==0.30.1",
    "autograd==1.8.0",
    "autograd-gamma==0.5.0",

    # Visualization Enhancement
    "SciencePlots==2.2.0",
    "latex==0.7.0",

    # Mathematical Formulas
    "formulaic==1.2.1",

    # Data Compatibility
    "narwhals==2.16.0"
    ]

[project.scripts]
myapp = "TumorVolumetricsApp.main:main"
